### ISSUE TITLE
Error when specifying both path to ncbi binaries and db folder interactively?

### ISSUE THREAD

**Issue by wwood** [yannickwurm/sequenceserver#137]
```
bash-3.2$ sequenceserver

Could not locate BLAST+ binaries.

SequenceServer can use NCBI BLAST+ that you may have on your system already, or
download the correct package for itself. Please enter the path to NCBI BLAST+
or press Enter to download.

Press Ctrl+C to quit.

>> /Users/ben/Downloads/ncbi-blast-2.2.30+/bin


Database dir not set.

SequenceServer needs to know where your FASTA files or BLAST+ databases are.
Please enter the path to the relevant directory (default: current directory).

Press Ctrl+C to quit.

>> /Users/ben/Downloads/db

Could not find BLAST+ databases in: /Users/ben/Downloads/db.
/Library/Ruby/Gems/2.0.0/gems/sequenceserver-1.0.0.pre.4/bin/sequenceserver:308:in `rescue in block (2 levels) in <top (required)>': undefined method `[]' for SequenceServer:Module (NoMethodError)
        from /Library/Ruby/Gems/2.0.0/gems/sequenceserver-1.0.0.pre.4/bin/sequenceserver:132:in `block (2 levels) in <top (required)>'
        from /Library/Ruby/Gems/2.0.0/gems/slop-3.6.0/lib/slop.rb:260:in `call'
        from /Library/Ruby/Gems/2.0.0/gems/slop-3.6.0/lib/slop.rb:260:in `parse!'
        from /Library/Ruby/Gems/2.0.0/gems/slop-3.6.0/lib/slop.rb:65:in `parse!'
        from /Library/Ruby/Gems/2.0.0/gems/sequenceserver-1.0.0.pre.4/bin/sequenceserver:12:in `<top (required)>'
        from /usr/bin/sequenceserver:23:in `load'
        from /usr/bin/sequenceserver:23:in `<main>'
```
The line `Could not find BLAST+ databases in: /Users/ben/Downloads/db.` is odd since I did not specify that the blast binaries should be at that location

**Comment by vivekiitkgp** [comment]
> The line `Could not find BLAST+ databases in: /Users/ben/Downloads/db.` is odd since I did not specify that the blast binaries should be at that location

Sorry but I couldn't find anything odd here. Can you please elaborate a bit more?

**Comment by wwood** [comment]
Oh you are right, I misread that. 

Perhaps the problem is that there is no _formatted_ databases in that directory, just a single file `a.fasta`?

**Comment by vivekiitkgp** [comment]
Yes. No formatted file could be found.

**Comment by yeban** [comment]
Thanks for catching that @wwood.
