### ISSUE TITLE
Broken blast setup - should fail more elegantly. 

### ISSUE THREAD

**Issue by yannickwurm** [yannickwurm/sequenceserver#141]
Somehow my brew blast got corrupted or something?  Really weird: 

```
Yannick@n56-164 ~> sequenceserver                                                                                               1
dyld: Library not loaded: /usr/local/lib/gcc/x86_64-apple-darwin14.0.0/4.9.2/libgomp.1.dylib
  Referenced from: /usr/local/bin/blastdbcmd
  Reason: image not found
/Users/Yannick/.gem/ruby/2.1.3/gems/sequenceserver-1.0.0.pre.5/lib/sequenceserver.rb:185:in `assert_blast_installed_and_compatible': undefined method `>=' for nil:NilClass (NoMethodError)
	from /Users/Yannick/.gem/ruby/2.1.3/gems/sequenceserver-1.0.0.pre.5/lib/sequenceserver.rb:118:in `init_binaries'
	from /Users/Yannick/.gem/ruby/2.1.3/gems/sequenceserver-1.0.0.pre.5/lib/sequenceserver.rb:38:in `init'
	from /Users/Yannick/.gem/ruby/2.1.3/gems/sequenceserver-1.0.0.pre.5/bin/sequenceserver:133:in `block (2 levels) in <top (required)>'
	from /Users/Yannick/.gem/ruby/2.1.3/gems/slop-3.6.0/lib/slop.rb:260:in `call'
	from /Users/Yannick/.gem/ruby/2.1.3/gems/slop-3.6.0/lib/slop.rb:260:in `parse!'
	from /Users/Yannick/.gem/ruby/2.1.3/gems/slop-3.6.0/lib/slop.rb:65:in `parse!'
	from /Users/Yannick/.gem/ruby/2.1.3/gems/sequenceserver-1.0.0.pre.5/bin/sequenceserver:12:in `<top (required)>'
	from /Users/Yannick/.gem/ruby/2.1.3/bin/sequenceserver:23:in `load'
	from /Users/Yannick/.gem/ruby/2.1.3/bin/sequenceserver:23:in `<main>'
Yannick@n56-164 ~>                                                                      
```

This is a blast install problem:
```
Yannick@n56-164 ~> blastp                                                                                                                                                        1
dyld: Library not loaded: /usr/local/lib/gcc/x86_64-apple-darwin14.0.0/4.9.2/libgomp.1.dylib
  Referenced from: /usr/local/bin/blastp
  Reason: image not found
[1]    17705 trace trap  blastp
```

Have no idea why or how this happened; running 'brew remove blast' "fixed" this.  (currently reinstalling blast). 

Point is - if BLAST dies, we should fail elegantly.

**Comment by yeban** [comment]
Agreed. The blast setup is broken because you ran `brew upgrade`. Happens with me all the time. You will have to reinstall blast to fix it.

**Comment by yeban** [comment]
@yannickwurm Did you manage to fix your BLAST setup? I'm hoping you didn't so can test the fix :p.

**Comment by yannickwurm** [comment]
sorry @yeban - my setup is fixed; I'm sure you can figure out ways of breaking a blast install though!
